#!/bin/bash
# adapted from tokens script, for supervision files
# -Cem Bozsahin 2017, Ankara
sed -e 's/\%.*$//g' -e 's/:/ |:| /g' -e 's/=/ |=| /g' -e 's/\./ |\.| /g' -e ' s/\\/ |\\\\| /g' -e 's/\// |\/| /g' -e 's/\;/ |;| /g' -e 's/\,/ |\,| /g' -e 's/-->/ |-->| /g' -e 's/(/ |(| /g' -e 's/)/ |)| /g' -e 's/\^/ |\^| /g' -e 's/\*/ |*| /g' -e 's/\+/ |+| /g' -e 's/\[/ |\[| /g' -e 's/\]/ |\]| /g' -e 's/\&i/ (LAM x x) /g' $1|sed -e 's/ |:|[ ]*|=| / |:=| /g'|sed -e 's/"\(.*\) |\([,\.]\)| \(.*\)"/"\1\2\3"/g' -e 's/"\(.*\) |\([,\.]\)| \(.*\)"/"\1\2\3"/g'|sed -e '1,1s/^/(/' -e '$s/$/)/'  > $2
